on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: self-hosted
        steps:
        # checkout the repo 
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
